- app/controllers/CalculatorController.scala
- app/models/CalculationResult.scala
- app/models/CalculationResultModel.scala
- app/services/CalculationService.scala
- conf/app.routes
- conf/application.conf
- test/controllers/CalculatorControllerSpec.scala
- test/services/CalculationServiceSpec.scala
- re-purposed old message controller that's no longer required
> CGT-655: Added simple calculation endpoint

- app/controllers/CalculatorController.scala
- app/services/CalculationService.scala
- test/services/CalculationServiceSpec.scala
- Corrected the rounding issues
- corrected tests that were erroneously changed
- refactored code
> CGT-1003: Fixed rounding issue in calculation logic

- app/models/CalculationResultModel.scala
- app/services/CalculationService.scala
- test/controllers/CalculatorControllerSpec.scala
- test/services/CalculationServiceSpec.scala
Only merge with Frontend task CGT-1196
> Added functionality to return the AEA used in the calculation.

- app/controllers/resident/CalculatorController.scala
- app/services/CalculationService.scala
- test/controllers/resident/CalculatorControllerSpec.scala
- test/services/CalculationServiceSpec.scala
CGT-1410 is not completed until the frontend change is also merged.
> Added missing rounding to backend calculation.

- app/controllers/resident/properties/CalculatorController.scala
- app/controllers/resident/shares/CalculatorController.scala
- app/models/resident/ChargeableGainResultModel.scala
- app/models/resident/TaxOwedResultModel.scala
- app/services/CalculationService.scala
- test/controllers/resident/properties/CalculatorControllerSpec.scala
- test/services/CalculationServiceSpec.scala
> Added reliefs used to logic and result model for properties.

- app/common/validation/TaxRatesAndBandsValidation.scala
- app/controllers/TaxRatesAndBandsController.scala
- test/common/validation/TaxRatesAndBandsValidationSpec.scala
- test/controllers/TaxRatesAndBandsControllerSpec.scala
GET        /tax-rates-and-bands/max-full-aea        
GET        /tax-rates-and-bands/max-partial-aea     
GET        /tax-rates-and-bands/max-pa
> Finished validation for routes (shown in comment)

- project/MicroService.scala
- project/plugins.sbt
See [here](https://confluence.tools.tax.service.gov.uk/display/DTRG/SBT%2C+Artefacts%2C+Repositories+and+Resolvers+on+the+Tax+Platform) under 'SbtAutoBuild' for more info
> Removed some redundant sbt settings and updated plugin versions

- conf/app.routes
Merge with CGT-2036 on the Front end
> Changed getTaxYear parameter.

- app/common/validation/TaxRatesAndBandsValidation.scala
- app/config/taxRatesAndBands.scala
- app/controllers/TaxRatesAndBandsController.scala
- test/common/validation/TaxRatesAndBandsValidationSpec.scala
- test/config/TaxRatesAndBandsSpec.scala
- test/controllers/TaxRatesAndBandsControllerSpec.scala
Maybe don't merge before discussing with Mac but it shouldn't affect the frontend
> (Cgt 2793) - Calculator back-end change for updated tax rates 2017/18

- app/common/validation/TaxRatesAndBandsValidation.scala
- app/config/taxRatesAndBands.scala
- test/config/TaxRatesAndBandsSpec.scala
Added for TaxRatesAndBands20182019
> Adding new Tax rates and bands for the new tax year

- project/MicroService.scala
- project/microServiceBuild.scala
- project/plugins.sbt
Updating capital gains calculator to new build
> DL-1242 - Migrating to new build

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- .gitignore
- app/config/microserviceGlobal.scala
- app/config/microserviceWiring.scala
- project/microServiceBuild.scala
- project/plugins.sbt
**Bug fix**
* Play upgrade to support security fix, and dependency uplift
* Added PR template to `capital-gains-calculator`
> DL-1465 Play upgrade to support security fix

- app/controllers/TaxRatesAndBandsController.scala
- app/controllers/nonresident/CalculatorController.scala
- app/controllers/resident/properties/CalculatorController.scala
- app/controllers/resident/shares/CalculatorController.scala
- app/models/nonResident/NonResidentTotalGainRequestModel.scala
- app/services/CalculationService.scala
- project/MicroService.scala
- project/microServiceBuild.scala
- project/plugins.sbt
- test/controllers/TaxRatesAndBandsControllerSpec.scala
- test/controllers/nonresident/CalculatorControllerSpec.scala
- test/controllers/resident/properties/CalculatorControllerSpec.scala
- test/controllers/resident/shares/CalculatorControllerSpec.scala
- test/services/CalculationServiceSpec.scala
**Maintenance** 
Play 2.6 upgrades and appropriate test updates
- [ x]  I've made every effort to commit high quality, clean code and I have executed relevant static analyses to be sure
- [ x]  I've included appropriate tests with any code I've added (Unit, Integration, Acceptance etc.)
- [ x]  I've executed the acceptance test pack locally to ensure there are no functional regressions
- [ x]  I've added my code using logical, atomic commits, squashing as appropriate - including the JIRA issue number in the commit message
- [ x]  I've run a dependency check to ensure all dependencies are up to date
> Play 2.6 upgrade

- app/config/taxRatesAndBands.scala
- app/controllers/nonresident/CalculatorController.scala
- project/MicroService.scala
- project/build.properties
- project/microServiceBuild.scala
- project/plugins.sbt
- test/common/binders/CommonBindersSpec.scala
- test/common/binders/NonResidentCalculationBinderSpec.scala
- test/common/binders/NonResidentTimeApportionmentCalculationBinderSpec.scala
- test/common/binders/ResidentPropertyBindersSpec.scala
- test/common/binders/ResidentSharesBindersSpec.scala
- test/controllers/TaxRatesAndBandsControllerSpec.scala
- test/controllers/resident/properties/CalculatorControllerSpec.scala
**New feature** 
If any core dependencies are out of date, the build will fail as part of deployment.
> Fail build if dependencies are out of date

- project/microServiceBuild.scala
- project/plugins.sbt
**Maintenance**
Raised dependencies to latest supported versions.
> Dependency updates

- app/common/validation/SharesValidation.scala
- app/controllers/TaxRatesAndBandsController.scala
- app/controllers/nonresident/CalculatorController.scala
- app/controllers/resident/properties/CalculatorController.scala
- app/controllers/resident/shares/CalculatorController.scala
- build.sbt
- project/build.properties
- project/plugins.sbt
- test/common/DateSpec.scala
- test/common/RouteSpec.scala
- test/common/binders/CommonBindersSpec.scala
- test/common/binders/NonResidentCalculationBinderSpec.scala
- test/common/binders/NonResidentTimeApportionmentCalculationBinderSpec.scala
- test/common/binders/ResidentPropertyBindersSpec.scala
- test/common/binders/ResidentSharesBindersSpec.scala
- test/controllers/TaxRatesAndBandsControllerSpec.scala
- test/controllers/nonresident/CalculatorControllerSpec.scala
- test/controllers/resident/properties/CalculatorControllerSpec.scala
- test/controllers/resident/shares/CalculatorControllerSpec.scala
- test/services/CalculationServiceSpec.scala
Updated the Scala/sbt versions, along with warning removals.
The code changes are mostly `unused import` removals.
> DL-2882 - Update SBT + Scala Version on CGT

- app/common/Date.scala
- app/config/PrivateResidenceReliefDateUtils.scala
- app/config/taxRatesAndBands.scala
- app/services/CalculationService.scala
- test/common/validation/TaxRatesAndBandsValidationSpec.scala
- test/config/TaxRatesAndBandsSpec.scala
- test/controllers/TaxRatesAndBandsControllerSpec.scala
- test/services/CalculationServiceSpec.scala
> CGT Tax Year Changes (Private residence relief)

- app/config/taxRatesAndBands.scala
- project/build.properties
- project/plugins.sbt
- test/config/TaxRatesAndBandsSpec.scala
> DL-5173 - updated tax bands for april 2021

- app/config/PrivateResidenceReliefDateUtils.scala
- app/config/taxRatesAndBands.scala
- app/services/CalculationService.scala
- conf/application.conf
- project/AppDependencies.scala
> DL-5428 - Bootstrap 2.7 upgraded to v4.2.0

- build.sbt
- project/AppDependencies.scala
- project/plugins.sbt
> DL-5462 Auth client upgrade

- project/AppDependencies.scala
- project/build.properties
- project/plugins.sbt
> DL-5744 Play 2.8 upgrade

- app/config/taxRatesAndBands.scala
- test/config/TaxRatesAndBandsSpec.scala
> update validation for year 2023

- app/config/taxRatesAndBands.scala
- app/controllers/TaxRatesAndBandsController.scala
- conf/app.routes
- test/config/TaxRatesAndBandsSpec.scala
- test/controllers/TaxRatesAndBandsControllerSpec.scala
> DL-7716 - Rate changes for the current financial year

- app/common/validation/CommonValidation.scala
- test/common/validation/CommonValidationSpec.scala
Updated validation to include Marriage Allowance
> DL-7716 - Amended personalAllowance validation

- build.sbt
- project/AppDependencies.scala
- project/build.properties
- project/plugins.sbt
- test/common/RouteSpec.scala
- test/common/binders/CommonBindersSpec.scala
- test/common/binders/NonResidentCalculationBinderSpec.scala
- test/common/binders/NonResidentTimeApportionmentCalculationBinderSpec.scala
- test/common/binders/ResidentPropertyBindersSpec.scala
- test/common/binders/ResidentSharesBindersSpec.scala
- test/controllers/TaxRatesAndBandsControllerSpec.scala
- test/controllers/nonresident/CalculatorControllerSpec.scala
- test/controllers/resident/properties/CalculatorControllerSpec.scala
- test/controllers/resident/shares/CalculatorControllerSpec.scala
- test/services/CalculationServiceSpec.scala
> DL-10009 java11 and dependency upgrade

- README.md
> DL-9844 Update README.md

- app/common/validation/CommonValidation.scala
- app/controllers/TaxRatesAndBandsController.scala
- build.sbt
- conf/application-json-logger.xml
- conf/application.conf
- it/testutils/nonResident/NonResidentComponentTest.scala
- project/AppDependencies.scala
- test/common/RouteSpec.scala
- test/common/binders/NonResidentCalculationBinderSpec.scala
- test/common/binders/NonResidentTimeApportionmentCalculationBinderSpec.scala
- test/controllers/TaxRatesAndBandsControllerSpec.scala
- test/controllers/nonresident/CalculatorControllerSpec.scala
DL-11197
- Refactored AppDependencies to use correct test & it test scopes
- Updated dependencies
- Cleared up warnings
- Fixed it tests that were not running
- Actioned PR bot
> DL-11197 Dependencies updated & refactored

- app/common/validation/TaxRatesAndBandsValidation.scala
- app/config/PrivateResidenceReliefDateUtils.scala
- app/config/taxRatesAndBands.scala
- project/AppDependencies.scala
- test/config/TaxRatesAndBandsSpec.scala
[DLS-10087](https://jira.tools.tax.service.gov.uk/browse/) - Add new tax year config
**New feature**
- Add new tax year config with changes to upper threshold and exemption amount. 
- Update tax year config list to exclude future tax year config based on current date.
> DLS-10087 | Add new tax year and tidyup tax year tests

- conf/application.conf
https://jira.tools.tax.service.gov.uk/browse/DLS-10172
Fix tax year go live date
> DLS-10172 | Fix tax year go live date

- build.sbt
- conf/prod.routes
- it/testutils/nonResident/NonResidentComponentTest.scala
- project/AppDependencies.scala
- project/build.properties
- project/plugins.sbt
- test/controllers/TaxRatesAndBandsControllerSpec.scala
> [DLS-10075] Upgrade to play 3.0
